name: nm_gql_go_link
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/google/note-maps/blob/main/packages/nm_gql_go_link

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  gql_link: ^0.2.3
  gql_exec: 
  #artemis: '>=5.0.0 <6.0.0' # only if you're using ArtemisClient!
  #json_serializable: ^3.0.0
  #equatable: ^0.6.1
  #meta: '>=1.0.0 <2.0.0' # only if you have non nullable fields
  #gql: '>=0.7.3 <1.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: '>=5.0.0 <6.0.0'
  build_runner: ^1.5.0
  json_serializable: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        pluginClass: NmGqlGoLinkPlugin
        package: com.example.nm_gql_go_link
      ios:
        pluginClass: NmGqlGoLinkPlugin
      linux:
        pluginClass: NmGqlGoLinkPlugin
      macos:
        pluginClass: NmGqlGoLinkPlugin
