name: Nix
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-stable
    - uses: cachix/cachix-action@v8
      with:
        name: note-maps
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix-shell --run "make download"
    - run: nix-shell --run "make lint"
    - run: nix-shell --run "make test"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-stable
    - uses: cachix/cachix-action@v8
      with:
        name: note-maps
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix-shell --run "make download"
    - run: nix-shell --run "make build"
    - uses: actions/upload-artifact@v2
      with:
        name: result
        path: ./out/
  deploy:
    needs:
    - build # produces the artifact
    - test  # but don't bother deploying if tests failed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: result
        path: ./out/
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: hosting:channel:deploy "$GITHUB_SHA"
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: note-maps
        PROJECT_PATH: ./build/firebase/
